# Generated by Django 3.2.23 on 2026-03-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('full_name_am', models.CharField(blank=True, max_length=200, verbose_name='Full Name (Amharic)')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_alt', models.CharField(blank=True, max_length=20, verbose_name='Alternative Phone')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region / Kifle Ketema')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('woreda', models.CharField(blank=True, max_length=100)),
                ('kebele', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(default='Ethiopian', max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='cv/photos/')),
                ('objective', models.TextField(blank=True, verbose_name='Career Objective / Summary')),
                ('employment_status', models.CharField(blank=True, choices=[('employed_full', 'Currently Employed (Full-time)'), ('employed_part', 'Currently Employed (Part-time)'), ('self_employed', 'Self-Employed / Freelancer'), ('unemployed', 'Unemployed / Looking for Work'), ('student', 'Student'), ('fresh_graduate', 'Fresh Graduate'), ('intern', 'Intern / Trainee')], max_length=30)),
                ('education_level', models.CharField(blank=True, choices=[('phd', 'PhD / Doctorate'), ('masters', "Master's Degree"), ('postgrad_dip', 'Postgraduate Diploma'), ('bachelor', "Bachelor's Degree (BSc / BA / BEd / BEng)"), ('advanced_dip', 'Advanced Diploma (3-year TVET)'), ('diploma', 'Diploma (2-year TVET / College)'), ('level4', 'TVET Level IV Certificate'), ('level3', 'TVET Level III Certificate'), ('level2', 'TVET Level II Certificate'), ('level1', 'TVET Level I Certificate'), ('preparatory', 'Preparatory (Grade 11–12)'), ('secondary', 'Secondary School (Grade 9–10)'), ('primary', 'Primary School (Grade 1–8)'), ('informal', 'Informal / Non-formal Education'), ('no_formal', 'No Formal Education'), ('other', 'Other / Self-taught / Vocational')], max_length=30)),
                ('field_of_study', models.CharField(blank=True, choices=[('civil_eng', 'Civil Engineering'), ('electrical_eng', 'Electrical Engineering'), ('mechanical_eng', 'Mechanical Engineering'), ('software_eng', 'Software Engineering'), ('computer_science', 'Computer Science / IT'), ('architecture', 'Architecture'), ('construction', 'Construction Technology'), ('water_resource', 'Water Resource Engineering'), ('environmental_eng', 'Environmental Engineering'), ('accounting', 'Accounting & Finance'), ('economics', 'Economics'), ('management', 'Management'), ('marketing', 'Marketing'), ('banking_finance', 'Banking & Finance'), ('logistics', 'Logistics & Supply Chain'), ('medicine', 'Medicine (MD)'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('public_health', 'Public Health'), ('midwifery', 'Midwifery'), ('health_officer', 'Health Officer'), ('medical_lab', 'Medical Laboratory'), ('education', 'Education / Teaching'), ('special_needs', 'Special Needs Education'), ('law', 'Law (LLB)'), ('social_work', 'Social Work'), ('journalism', 'Journalism & Communication'), ('political_science', 'Political Science'), ('sociology', 'Sociology'), ('psychology', 'Psychology'), ('agriculture', 'Agriculture'), ('animal_science', 'Animal Science / Veterinary'), ('natural_resource', 'Natural Resource Management'), ('amharic', 'Amharic Language & Literature'), ('english', 'English Language & Literature'), ('history', 'History'), ('geography', 'Geography'), ('auto_mechanics', 'Automotive Mechanics'), ('electricity', 'Electricity / Electrical Installation'), ('welding', 'Welding & Metal Fabrication'), ('garment', 'Garment & Textile'), ('hotel_tourism', 'Hotel & Tourism'), ('ict_tvet', 'ICT (TVET)'), ('other_field', 'Other')], max_length=50)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.CharField(blank=True, max_length=4)),
                ('cgpa', models.CharField(blank=True, max_length=10, verbose_name='CGPA / GPA')),
                ('cgpa_scale', models.CharField(blank=True, default='4.0', max_length=5, verbose_name='GPA Scale (e.g. 4.0)')),
                ('exit_exam_score', models.CharField(blank=True, max_length=10, verbose_name='Exit Exam Score (%)')),
                ('exit_exam_year', models.CharField(blank=True, max_length=4, verbose_name='Exit Exam Year')),
                ('thesis_title', models.CharField(blank=True, max_length=300, verbose_name='Thesis / Research Title')),
                ('tvet_level', models.CharField(blank=True, max_length=20, verbose_name='TVET Level (I–IV)')),
                ('tvet_center', models.CharField(blank=True, max_length=200, verbose_name='TVET Center / College')),
                ('tvet_year', models.CharField(blank=True, max_length=4, verbose_name='Year Completed')),
                ('competency_areas', models.TextField(blank=True, verbose_name='Competency Areas')),
                ('technical_skills', models.TextField(blank=True, verbose_name='Technical Skills (comma separated)')),
                ('soft_skills', models.TextField(blank=True, verbose_name='Soft Skills (comma separated)')),
                ('computer_skills', models.TextField(blank=True, verbose_name='Computer / IT Skills')),
                ('driving_license', models.BooleanField(default=False)),
                ('driving_license_type', models.CharField(blank=True, max_length=20, verbose_name='License Type (A, B, C, D, F)')),
                ('has_experience', models.BooleanField(default=False)),
                ('experience_years', models.CharField(blank=True, max_length=5, verbose_name='Total Years of Experience')),
                ('experience_detail', models.TextField(blank=True, verbose_name='Work Experience Details')),
                ('amharic_level', models.CharField(choices=[('native', 'Native'), ('fluent', 'Fluent'), ('professional', 'Professional Working'), ('intermediate', 'Intermediate'), ('basic', 'Basic')], default='native', max_length=20)),
                ('english_level', models.CharField(blank=True, choices=[('native', 'Native'), ('fluent', 'Fluent'), ('professional', 'Professional Working'), ('intermediate', 'Intermediate'), ('basic', 'Basic')], max_length=20)),
                ('other_languages', models.CharField(blank=True, max_length=200, verbose_name='Other Languages (e.g. Oromiffa, Tigrinya)')),
                ('references', models.TextField(blank=True, verbose_name='References (Name, Title, Phone)')),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to='cv/transcripts/')),
                ('exit_exam_file', models.FileField(blank=True, null=True, upload_to='cv/exit_exams/')),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to='cv/degrees/')),
                ('tvet_certificate', models.FileField(blank=True, null=True, upload_to='cv/tvet/')),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='cv/experience/')),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='cv/recommendations/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='cv/other/')),
                ('other_document_label', models.CharField(blank=True, max_length=100)),
                ('is_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
