# Generated by Django 3.2.23 on 2026-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('full_name_am', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('grandfather_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_alt', models.CharField(blank=True, max_length=20)),
                ('phone_alt2', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('sub_city', models.CharField(blank=True, max_length=100)),
                ('woreda', models.CharField(blank=True, max_length=50)),
                ('kebele', models.CharField(blank=True, max_length=50)),
                ('house_number', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(default='Ethiopian', max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.CharField(blank=True, default='', max_length=20)),
                ('disability', models.CharField(blank=True, default='None', max_length=50)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='cv/photos/')),
                ('skill_category', models.CharField(blank=True, max_length=30)),
                ('skill_title', models.CharField(blank=True, max_length=100)),
                ('skill_title_custom', models.CharField(blank=True, max_length=100)),
                ('skill_specialization', models.CharField(blank=True, max_length=200, verbose_name='Specialization / Subject / Department')),
                ('objective', models.TextField(blank=True)),
                ('employment_status', models.CharField(blank=True, max_length=50)),
                ('education_entries', models.TextField(blank=True, default='[]', verbose_name='Education entries (JSON)')),
                ('education_level', models.CharField(blank=True, max_length=30)),
                ('field_of_study', models.CharField(blank=True, max_length=50)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.CharField(blank=True, max_length=4)),
                ('cgpa', models.CharField(blank=True, max_length=10)),
                ('cgpa_scale', models.CharField(blank=True, default='4.0', max_length=5)),
                ('exit_exam_score', models.CharField(blank=True, max_length=10)),
                ('exit_exam_year', models.CharField(blank=True, max_length=4)),
                ('thesis_title', models.CharField(blank=True, max_length=300)),
                ('technical_skills', models.TextField(blank=True, verbose_name='Technical Skills (comma separated)')),
                ('soft_skills', models.TextField(blank=True, verbose_name='Soft Skills (comma separated)')),
                ('computer_skills', models.TextField(blank=True, verbose_name='Computer / IT Skills')),
                ('driving_license', models.BooleanField(default=False)),
                ('driving_license_type', models.CharField(blank=True, max_length=20, verbose_name='License Type (A, B, C, D, F)')),
                ('has_experience', models.BooleanField(default=False)),
                ('experience_years', models.CharField(blank=True, max_length=5)),
                ('experience_entries', models.TextField(blank=True, default='[]', verbose_name='Experience entries (JSON)')),
                ('experience_detail', models.TextField(blank=True)),
                ('reference_1', models.CharField(blank=True, max_length=300)),
                ('reference_2', models.CharField(blank=True, max_length=300)),
                ('amharic_level', models.CharField(blank=True, default='Native', max_length=20)),
                ('english_level', models.CharField(blank=True, max_length=20)),
                ('other_languages', models.CharField(blank=True, max_length=200)),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to='cv/transcripts/')),
                ('exit_exam_file', models.FileField(blank=True, null=True, upload_to='cv/exit_exams/')),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to='cv/degrees/')),
                ('tvet_certificate', models.FileField(blank=True, null=True, upload_to='cv/tvet/')),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='cv/experience/')),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='cv/recommendations/')),
                ('national_id', models.FileField(blank=True, null=True, upload_to='cv/ids/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='cv/other/')),
                ('other_document_label', models.CharField(blank=True, max_length=100)),
                ('is_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
