# Generated by Django 3.2.23 on 2026-04-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_cv_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='other_languages',
            field=models.TextField(blank=True),
        ),
    ]
