# Generated by Django 3.2.23 on 2026-03-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_cv_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='competency_areas',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='references',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='tvet_center',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='tvet_level',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='tvet_year',
        ),
        migrations.AddField(
            model_name='cv',
            name='disability',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='cv',
            name='education_entries',
            field=models.TextField(blank=True, default='[]', verbose_name='Education entries (JSON)'),
        ),
        migrations.AddField(
            model_name='cv',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='grandfather_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='house_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cv',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='national_id',
            field=models.FileField(blank=True, null=True, upload_to='cv/ids/'),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone_alt2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='reference_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='cv',
            name='reference_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='cv',
            name='sub_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='amharic_level',
            field=models.CharField(blank=True, default='Native', max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='cgpa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cv',
            name='cgpa_scale',
            field=models.CharField(blank=True, default='4.0', max_length=5),
        ),
        migrations.AlterField(
            model_name='cv',
            name='date_of_birth',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='education_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cv',
            name='english_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='exit_exam_score',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cv',
            name='exit_exam_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experience_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experience_years',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='cv',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='full_name_am',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='other_languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='thesis_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='cv',
            name='woreda',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
