# Generated by Django 3.2.23 on 2026-03-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0003_auto_20260328_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='objective',
        ),
    ]
