# Generated by Django 3.2.23 on 2026-03-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0004_auto_20260328_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cv',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='skill_category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cv',
            name='skill_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='skill_title_custom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
