# Generated by Django 3.2.23 on 2026-03-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0005_auto_20260328_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='skill_specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Specialization / Subject / Department'),
        ),
    ]
