# Generated by Django 3.2.23 on 2026-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_am', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_am', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level')], max_length=20)),
                ('industry', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='fulltime', max_length=20)),
                ('salary', models.CharField(blank=True, max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft - Pending Review'), ('under_review', 'Under Admin Review'), ('approved', 'Approved - Awaiting Payment'), ('payment_pending', 'Payment Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin note to employer')),
                ('posting_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fee set by admin (ETB)')),
                ('fee_paid', models.BooleanField(default=False)),
                ('fee_tx_ref', models.CharField(blank=True, max_length=200, verbose_name='Chapa tx_ref for fee')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
