# Generated by Django 3.2.23 on 2026-03-27 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_job_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Admin note to employer'),
        ),
        migrations.AddField(
            model_name='job',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='fee_tx_ref',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chapa tx_ref for fee'),
        ),
        migrations.AddField(
            model_name='job',
            name='posting_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fee set by admin (ETB)'),
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Pending Review'), ('under_review', 'Under Admin Review'), ('approved', 'Approved - Awaiting Payment'), ('payment_pending', 'Payment Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
