# Generated by Django 3.2.23 on 2026-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extend_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='extend_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='extend_fee_tx_ref',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='extend_new_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='extend_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='extend_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('fee_set', 'Fee Set'), ('paid', 'Paid'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
