# Generated by Django 3.2.23 on 2026-03-28 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_type', models.CharField(choices=[('company', 'Company / PLC / Corporation'), ('factory', 'Factory / Manufacturing'), ('ngo', 'NGO / Organization'), ('shop', 'Shop / Small Business'), ('individual', 'Individual / Freelancer'), ('other', 'Other')], max_length=20)),
                ('employer_type_other', models.CharField(blank=True, max_length=100)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('business_license', models.FileField(blank=True, null=True, upload_to='employer_docs/licenses/')),
                ('tin_certificate', models.FileField(blank=True, null=True, upload_to='employer_docs/tin/')),
                ('registration_cert', models.FileField(blank=True, null=True, upload_to='employer_docs/reg/')),
                ('national_id_front', models.ImageField(blank=True, null=True, upload_to='employer_docs/national_id/')),
                ('national_id_back', models.ImageField(blank=True, null=True, upload_to='employer_docs/national_id/')),
                ('national_id_number', models.CharField(blank=True, max_length=50)),
                ('supporting_doc', models.FileField(blank=True, null=True, upload_to='employer_docs/supporting/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
